config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('purchase_data.urls', namespace='purchase_data')),
    path('accounts/', include('allauth.urls')),
   # path('', include('accounts.urls')), 
]

purchase_data/urls.py
from django.urls import path
from . import views
 
app_name = 'purchase_data'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    #path('index/', views.IndexView.as_view(), name='index'),
    path('item/create/', views.ItemCreateView.as_view(), name='item_create'),
    path('item/create/complete', views.ItemCreateCompleteView.as_view(), name='item_create_complete'),
    path('item/list/', views.ItemListView.as_view(),name='item_list'),
    path('item/detail/<uuid:pk>/', views.ItemDetailView.as_view(), name='item_detail'), 
    path('item/update/<uuid:pk>/', views.ItemUpdateView.as_view(), name='item_update'),
    path('item/delete/<uuid:pk>/', views.ItemDeleteView.as_view(), name='item_delete'),
    path('purchase_data/create/', views.PurchaseDataCreateView.as_view(), name='purchase_data_create'),
    path('purchase_data/create/complete', views.PurchaseDataCreateCompleteView.as_view(), name='purchase_data_create_complete'),
    path('purchase_data/list/', views.PurchaseDataListView.as_view(),name='purchase_data_list'),
    path('purchase_data/detail/<uuid:pk>/', views.PurchaseDataDetailView.as_view(), name='purchase_data_detail'), 
    path('purchase_data/update/<uuid:pk>/', views.PurchaseDataUpdateView.as_view(), name='purchase_data_update'),
    path('purchase_data/delete/<uuid:pk>/', views.PurchaseDataDeleteView.as_view(), name='purchase_data_delete'),
]

purchase_data_Tomakomai/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

purchase_data/models.py
from django.core import validators
from django.db import models
from django.utils import timezone
import uuid

# Create your models here.
class Item(models.Model):
    class Meta:
        db_table    = "item"


    CATEGORY_CHOICES = (
        ('食品', '食品'),
        ('飲料', '飲料'),
        ('家電', '家電・カメラ'),
        ('PC・スマホ・通信', 'PC・スマホ・通信'),
        ('日用雑貨・キッチン用品', '日用雑貨・キッチン用品'),
        ('コスメ・健康・医薬品', 'コスメ・健康・医薬品'),
        ('インテリア・寝具', 'インテリア・寝具'),
        ('服飾・ファッション', '服飾・ファッション'),
        ('スポーツ', 'スポーツ'),
        ('本・電子書籍・音楽', '本・電子書籍・音楽'),
        ('キッズ・ベビー・玩具', 'キッズ・ベビー・玩具'),
        ('ゲーム・ホビー・楽器', 'ゲーム・ホビー・楽器'),
        ('車・バイク', '車・バイク'),
        ('ペット・花・DIY', 'ペット・花・DIY'),
        ('サービス・リフォーム', 'サービス・リフォーム'),
        ('その他', 'その他'),
    )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(verbose_name="品名",max_length=100)
    price = models.IntegerField(verbose_name="価格")
    category = models.CharField(verbose_name="カテゴリー",choices=CATEGORY_CHOICES,max_length=100)
    created_at = models.DateTimeField(verbose_name='作成日時', default=timezone.now)
    updated_at = models.DateTimeField(verbose_name='編集日時', blank=True, null=True)

    def __str__(self):
        return self.name

class PurchaseData(models.Model):
    class Meta:
        db_table    = "purchase_data"

    GENDER_CHOICES = (
        ('女性', '女性'),
        ('男性', '男性'),
        ('その他・無回答', 'その他・無回答'),
    )

    AGE_CHOICES = (
        ('〜19歳', '〜19歳'),
        ('20代', '20代'),
        ('30代', '30代'),
        ('40代', '40代'),
        ('50代', '50代'),
        ('60代', '60代'),
        ('70代', '70代'),
        ('80代〜', '80代〜'),
        ('不明・無回答', '不明・無回答'),
    )

    PLACE_CHOICES=(
        ('青葉町','青葉町'),
        ('明野新町','明野新町'),
        ('明野元町','明野元町'),
        ('あけぼの町','あけぼの町'),
        ('旭町','旭町'),
        ('有明町','有明町'),
        ('泉町','泉町'),
        ('一本松町','一本松町'),
        ('字糸井','字糸井'),
        ('入船町','入船町'),
        ('字植苗','字植苗'),
        ('有珠の沢町','有珠の沢町'),
        ('ウトナイ北','ウトナイ北'),
        ('ウトナイ南','ウトナイ南'),
        ('永福町','永福町'),
        ('王子町','王子町'),
        ('大町','大町'),
        ('音羽町','音羽町'),
        ('表町','表町'),
        ('柏木町','柏木町'),
        ('字柏原','字柏原'),
        ('春日町','春日町'),
        ('川沿町','川沿町'),
        ('木場町','木場町'),
        ('錦西町','錦西町'),
        ('啓北町','啓北町'),
        ('小糸井町','小糸井町'),
        ('光洋町','光洋町'),
        ('寿町','寿町'),
        ('幸町','幸町'),
        ('栄町','栄町'),
        ('桜木町','桜木町'),
        ('桜坂町','桜坂町'),
        ('三光町','三光町'),
        ('汐見町','汐見町'),
        ('字静川','字静川'),
        ('清水町','清水町'),
        ('しらかば町','しらかば町'),
        ('白金町','白金町'),
        ('新開町','新開町'),
        ('新富町','新富町'),
        ('新中野町','新中野町'),
        ('新明町','新明町'),
        ('末広町','末広町'),
        ('澄川町','澄川町'),
        ('住吉町','住吉町'),
        ('青雲町','青雲町'),
        ('大成町','大成町'),
        ('字高丘','字高丘'),
        ('高砂町','高砂町'),
        ('拓勇西町','拓勇西町'),
        ('拓勇東町','拓勇東町'),
        ('字樽前','字樽前'),
        ('東開町','東開町'),
        ('ときわ町','ときわ町'),
        ('豊川町','豊川町'),
        ('錦町','錦町'),
        ('字錦岡','字錦岡'),
        ('日新町','日新町'),
        ('字沼ノ端','字沼ノ端'),
        ('沼ノ端中央','沼ノ端中央'),
        ('のぞみ町','のぞみ町'),
        ('花園町','花園町'),
        ('浜町','浜町'),
        ('はまなす町','はまなす町'),
        ('晴海町','晴海町'),
        ('日の出町','日の出町'),
        ('日吉町','日吉町'),
        ('双葉町','双葉町'),
        ('船見町','船見町'),
        ('字弁天','字弁天'),
        ('北栄町','北栄町'),
        ('北星町','北星町'),
        ('北光町','北光町'),
        ('本町','本町'),
        ('本幸町','本幸町'),
        ('真砂町','真砂町'),
        ('松風町','松風町'),
        ('字丸山','字丸山'),
        ('字美沢','字美沢'),
        ('美園町','美園町'),
        ('緑町','緑町'),
        ('港町','港町'),
        ('美原町','美原町'),
        ('宮の森町','宮の森町'),
        ('見山町','見山町'),
        ('宮前町','宮前町'),
        ('明徳町','明徳町'),
        ('もえぎ町','もえぎ町'),
        ('元町','元町'),
        ('元中野町','元中野町'),
        ('矢代町','矢代町'),
        ('柳町','柳町'),
        ('山手町','山手町'),
        ('弥生町','弥生町'),
        ('字勇払','字勇払'),
        ('若草町','若草町'),
    )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    #detail = models.CharField(max_length=200)
    date = models.DateTimeField(verbose_name='購買日時')
    #place = models.CharField(verbose_name='商品受け渡し場所', max_length=40)
    place = models.CharField(verbose_name='商品受け渡し場所', choices=PLACE_CHOICES,max_length=40)
    gender = models.CharField(verbose_name='性別', choices=GENDER_CHOICES, max_length=20)
    age = models.CharField(verbose_name='年齢', choices=AGE_CHOICES, max_length=20)
    item = models.ManyToManyField(Item, verbose_name="購入商品", related_name='purchase_data', blank=True)
    created_at = models.DateTimeField(verbose_name='作成日時', default=timezone.now)
    updated_at = models.DateTimeField(verbose_name='編集日時', blank=True, null=True)

    def __str__(self):
        return self.place

class PurchaseDataDetail(models.Model):
    purchase_data = models.ForeignKey(
        PurchaseData,
        on_delete=models.PROTECT)

    item = models.ForeignKey(Item, verbose_name="購入商品", on_delete=models.PROTECT, default=1,)

    quantity = models.IntegerField(
        verbose_name='数量',
        default = 0
    )

    def __str__(self):
        return self.purchase_data.place

 

    

purchase_data/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from .models import Item, PurchaseData, PurchaseDataDetail

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'price', 'category')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
        }

class PurchaseDataForm(forms.ModelForm):
    item = forms.ModelMultipleChoiceField(
        label = '購入商品',
        queryset=Item.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'form-control'})
    )

    class Meta:
        model = PurchaseData
        fields = ('date', 'place', 'gender', 'age', 
        'item'
        )
        widgets = {
            'date': forms.DateTimeInput(attrs={'class': 'form-control', "type": "datetime-local"}),
            'place': forms.Select(attrs={'class': 'form-control'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),
            'age': forms.Select(attrs={'class': 'form-control'}),
            'item': forms.CheckboxSelectMultiple(attrs={'class': 'form-control'})
        }
    
    def clean_items(self):
        item = self.cleaned_data.get("item")
        items_list = item.split(",")
        return items_list

class PurchaseDataDetailForm(forms.ModelForm):
    item = forms.ModelMultipleChoiceField(
        label = '購入商品',
        queryset=Item.objects.all(),
    #    widget=forms.CheckboxSelectMultiple(attrs={'class': 'form-control'})
    )

    class Meta:
        model = PurchaseDataDetail
        fields = ('item','quantity',)

    #def __init__(self, *args, **kwargs):
    #    super(PurchaseDataDetailForm, self).__init__(*args, **kwargs)
#
    #    self.fields['item'].choices = lambda: [('', '-- 商品 --')] + [
    #        (item.id, '%s %s円' % (item.name.ljust(10, '　'), item.price)) for item in
    #        Item.objects]
#
    #    choices_number = [('', '-- 個数 --')] + [(str(i), str(i)) for i in range(1, 10)]
    #    self.fields['quantity'].widget = forms.widgets.Select(choices=choices_number)
    
    def clean_items(self):
        item = self.cleaned_data.get("item")
        items_list = item.split(",")
        return items_list

PurchaseDataDetailFormSet = inlineformset_factory(
    parent_model=PurchaseData,
    model=PurchaseDataDetail,
    form=PurchaseDataDetailForm,
    extra=1,
    min_num=1,
    validate_min=True,
)

purchase_data/views.py
from django.views.generic import TemplateView, CreateView, ListView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.utils import timezone
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django import forms
from .forms import ItemForm, PurchaseDataForm, PurchaseDataDetailForm, PurchaseDataDetailFormSet
from .models import Item, PurchaseData
from . import draw_utils

class IndexView(TemplateView):
    template_name = 'index.html'

class ItemCreateView(CreateView):
    template_name = 'item/item_create.html'
    form_class = ItemForm
    success_url = reverse_lazy('purchase_data:item_create_complete')

class PurchaseDataCreateView(CreateView):

    model = PurchaseData
    template_name = 'purchase_data/purchase_data_create.html'
    form_class = PurchaseDataForm
    #formset_class = PurchaseDataDetailFormSet
    success_url = reverse_lazy('purchase_data:purchase_data_create_complete')

    def get(self, request, *args, **kwargs):
        
        #items   = Item.objects.all()
        form_class = PurchaseDataForm
        #form_detail_class = PurchaseDataDetailForm
        context = { "form": form_class,
                    #"form_detail": form_detail_class,
                    #"items": items 
                }

        return render(request,"purchase_data/purchase_data_create.html",context)

    def post(self, request, *args, **kwargs):

        form = PurchaseDataForm(request.POST)

        if form.is_valid():
            print("バリデーションOK")
            form.save()
            return redirect("purchase_data:purchase_data_create_complete")

        else:
            print("バリデーションNG")
            print(form.errors)

        return redirect("purchase_data:purchase_data_create")
    
    
class ItemCreateCompleteView(TemplateView):
    template_name = 'item/item_create_complete.html'

class PurchaseDataCreateCompleteView(TemplateView):
    template_name = 'purchase_data/purchase_data_create_complete.html'

class ItemListView(ListView):
    template_name = 'item/item_list.html'
    model = Item

class PurchaseDataListView(ListView): ###
    template_name = 'purchase_data/purchase_data_list.html'
    model = PurchaseData

    def get(self, request):
        data    = PurchaseData.objects.all()

        m = draw_utils.visualize_locations()
        m2 = draw_utils.visualize_locations2()
        barfig =draw_utils.draw_graph() 
        circlefig = draw_utils.draw_circle()
        age_cirfig = draw_utils.draw_circle_age()
        gender_cirfig = draw_utils.draw_circle_gender()
        tabe_cirfig = draw_utils.draw_circle_tabe()
        m3 = draw_utils.visualize_locations3()
        rank=draw_utils.draw_rank()
        n = draw_utils.get_num()
        context = { "purchase_data_list":data,
                    'map':m,
                    'map2':m2,
                    'map3':m3,
                    'bar':barfig,
                    'circle':circlefig,
                    'circle_age':age_cirfig,
                    'circle_gender':gender_cirfig,
                    'circle_tabe':tabe_cirfig,
                    'rank':rank,
                    'num':n
                    }
        return render(request,"purchase_data/purchase_data_list.html",context)

class ItemDetailView(DetailView):
    template_name = 'item/item_detail.html'
    model = Item

class PurchaseDataDetailView(DetailView):
    template_name = 'purchase_data/purchase_data_detail.html'
    model = PurchaseData

class ItemUpdateView(UpdateView):
    template_name = 'item/item_update.html'
    model = Item
    fields = ('name', 'price', 'category')
    success_url: reverse_lazy('purchase_data:item_list')
 
    def form_valid(self, form):
        item = form.save(commit=False)
        item.updated_at = timezone.now()
        item.save()
        return super().form_valid(form)

class PurchaseDataUpdateView(UpdateView):
    template_name = 'purchase_data/purchase_data_update.html'
    model = PurchaseData
    fields = ('date', 'place', 'gender', 'age', 'item')
    success_url: reverse_lazy('purchase_data:purchase_data_list')
 
    def form_valid(self, form):
        purchase_data = form.save(commit=False)
        purchase_data.updated_at = timezone.now()
        purchase_data.save()
        return super().form_valid(form)

class ItemDeleteView(DeleteView):
    template_name = 'item/item_delete.html'
    model = Item
    success_url = reverse_lazy('purchase_data:item_list')

class PurchaseDataDeleteView(DeleteView):
    template_name = 'purchase_data/purchase_data.html'
    model = PurchaseData
    success_url = reverse_lazy('purchase_data:purchase_data_list')

templates/purchase_data/purchase_data_create.html
{% extends 'base.html' %} {% load widget_tweaks %} {% block extra_head %}
<h1 class="m-0">購入データの登録</h1>
{% endblock %} {% block content %}
<form method="post">
    {% csrf_token %} {{ data.as_p }}

    <div class="form-group">
        <label>{{ form.date.label }}</label>{{ form.date | add_class:'form-control col-3' }}
    </div>
    <div class="form-group">
        <label>{{ form.place.label }}</label>{{ form.place | add_class:'form-control col-3' }}
    </div>
    <div class="form-group">
        <label>{{ form.gender.label }}</label> {{ form.gender | add_class:'form-control col-3' }}
    </div>
    <div class="form-group">
        <label>{{ form.age.label }}</label> {{ form.age | add_class:'form-control col-3' }}
    </div>
    <div class="form-group">
        <label>{{ form.item.label }}</label>
        <br> {% for item in form.item %} {{ item }}{% endfor %}
    </div>
    <div class="form-group">
        <table class="table table-sm table-striped table-bordered ">
            <thead class="thead-dark">
                <tr>
                    <th>商品名</th>
                    <th>個数</th>
                </tr>
            </thead>
            <!--<tbody>
                {% for item in form.item %}
                <tr>
                    <td>{{ item }}</td>
                    <td class="number">{{ form.quantity }}</td>
                </tr>
                {% endfor %}
            </tbody>-->
        </table>
    </div>
    <a href="{% url 'purchase_data:index' %}">トップへ戻る</a>
    <button type="submit" name="submit">登録</button>
</form>
{% endblock %}

templates/purchase_data/purchase_data_create_complete.html
{% extends 'base.html' %} {% load widget_tweaks %} {% block content %}
<p>購買データの登録が完了しました！</p>
<a href="{% url 'purchase_data:index' %}">トップへ戻る</a> {% endblock %}

templates/purchase_data/purchase_data_delete.html
{% extends 'base.html' %} {% block content %}
<h1>購買データの削除</h1>
<form method="post">
    {% csrf_token %}
    <p>{{ item.id }} {{ item.name }} を削除します</p>
    <input type="submit" value="削除">
</form>
{% endblock %}

templates/purchase_data/purchase_data_detail.html
{% extends 'base.html' %} {% block content %}
<p>{{ purchase_data.date }}</p>
<p>{{ purchase_data.id }}</p>
<p>{{ purchase_data.place }}</p>
<p>{{ purchase_data.gender }}</p>
<p>{{ purchase_data.age }}</p>
<p>{{ purchase_data.item }}</p>
<a href="{% url 'purchase_data:purchase_data_update' purchase_data.pk %}">編集</a>
<a href="{% url 'purchase_data:purchase_data_delete' purchase_data.pk %}">削除</a>
<a href="{% url 'purchase_data:index' %}">戻る</a> {% endblock %}

templates/purchase_data/purchase_data_list.html
{% extends 'base.html' %} 
{% block content %} 
<h1>購入データの一覧</h1><h2>{{ num }}</h2>
<div class="flex">
    <div class="right">
        <table>
            <tr>
                <th>日付</th>
                <th>金額</th>
                <th>詳細</th>
                <th>カテゴリー</th>
                <th>場所</th>
                <th>性別</th>
                <th>年齢</th>
            </tr>
            {% for p in purchase_data_list %}
            {% for j in p.item.all %}
            <tr>
                <td>{{ p.date }}</td>
                <td>{{ j.price }}円</td>
                <td>{{ j.name }}</td>
                <td>{{ j.category }}</td>
                <td>{{ p.place }}</td>
                <td>{{ p.gender }}</td>
                <td>{{ p.age }}</td>
            </tr>
            {% endfor %}
            {% endfor %}
        </table>
    </div>
    <div class="left">
        <p>日ごとの販売額</p>
        <img src="data:image/png;base64,{{ bar | safe }}"
        width=40%>
    </div>
</div> 
<div class="flex">
    <div class="right">    
    <img src="data:image/png;base64,{{ circle | safe }}"
    width=40%></div>
    <div class="left"> <img src="data:image/png;base64,{{ rank | safe }}"
    width=40%></div>
</div>
<div class="flex">
    <div class="right">
    <img src="data:image/png;base64,{{ circle_age | safe }}"
    width=40%></div>
    <div class="left"><img src="data:image/png;base64,{{ circle_gender | safe }}"
    width=40%></div>
</div>
<div class="flex">
    <div class="left">
<p>取引金額</p> 

{{ map2|safe }}
    </div>
    <div class="right">
<p>カテゴリー別</p>
{{ map3|safe }}
    </div>
</div>
<p>人口</p>
{{ map|safe }}
<a href="{% url 'purchase_data:index' %}">戻る</a> {% endblock %}

templates/purchase_data/purchase_data_update.html
{% extends 'base.html' %} {% block content %}
<h1>購買データの編集</h1>
<form method="post">
    {% csrf_token %} {{ data.as_p }}

    <div class="form-group">
        <label>{{ form.date.label }}</label>{{ form.date | add_class:'form-control col-3' }}
    </div>
    <div class="form-group">
        <label>{{ form.place.label }}</label>{{ form.place | add_class:'form-control col-3' }}
    </div>
    <div class="form-group">
        <label>{{ form.gender.label }}</label> {{ form.gender | add_class:'form-control col-3' }}
    </div>
    <div class="form-group">
        <label>{{ form.age.label }}</label> {{ form.age | add_class:'form-control col-3' }}
    </div>
    <div class="form-group">
        <label>{{ form.item.label }}</label><br> {% for item in form.item %}
        <input id="{{ item.id }}" class="input_chk" type="checkbox" name="items" value="{{ item.id }}">
        <label class="surround_label" for="{{ item.id }}">{{ item }}</label> {% endfor %}
    </div>
    <a href="{% url 'purchase_data:index' %}">トップへ戻る</a>
    <input type="submit" value="保存">
</form>
{% endblock %}