config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('purchase_data.urls', namespace='purchase_data')),
    path('accounts/', include('allauth.urls')),
   # path('', include('accounts.urls')), 
]

purchase_data/urls.py
from django.urls import path
from . import views
 
app_name = 'purchase_data'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    #path('index/', views.IndexView.as_view(), name='index'),
    path('item/create/', views.ItemCreateView.as_view(), name='item_create'),
    path('item/create/complete', views.ItemCreateCompleteView.as_view(), name='item_create_complete'),
    path('item/list/', views.ItemListView.as_view(),name='item_list'),
    path('item/detail/<uuid:pk>/', views.ItemDetailView.as_view(), name='item_detail'), 
    path('item/update/<uuid:pk>/', views.ItemUpdateView.as_view(), name='item_update'),
    path('item/delete/<uuid:pk>/', views.ItemDeleteView.as_view(), name='item_delete'),
    path('purchase_data/create/', views.PurchaseDataCreateView.as_view(), name='purchase_data_create'),
    path('purchase_data/create/complete', views.PurchaseDataCreateCompleteView.as_view(), name='purchase_data_create_complete'),
    path('purchase_data/list/', views.PurchaseDataListView.as_view(),name='purchase_data_list'),
    path('purchase_data/detail/<uuid:pk>/', views.PurchaseDataDetailView.as_view(), name='purchase_data_detail'), 
    path('purchase_data/update/<uuid:pk>/', views.PurchaseDataUpdateView.as_view(), name='purchase_data_update'),
    path('purchase_data/delete/<uuid:pk>/', views.PurchaseDataDeleteView.as_view(), name='purchase_data_delete'),
]

purchase_data_Tomakomai/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

templates/base.html
{% load static %}
<!DOCTYPE html> {% load static %}
<html lang="jp">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PurchaseDataApp</title>

    <!--<link rel="stylesheet" type="text/css" href="{% static 'css/allauth.css' %}">-->

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'AdminLTE-3.2.0/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css' %}">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="{% static 'AdminLTE-3.2.0/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static 'AdminLTE-3.2.0/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
    <!-- JQVMap -->
    <link rel="stylesheet" href="{% static 'AdminLTE-3.2.0/plugins/jqvmap/jqvmap.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'AdminLTE-3.2.0/dist/css/adminlte.min.css' %}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{% static 'AdminLTE-3.2.0/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{% static 'AdminLTE-3.2.0/plugins/daterangepicker/daterangepicker.css' %}">
    <!-- summernote -->
    <link rel="stylesheet" href="{% static 'AdminLTE-3.2.0/plugins/summernote/summernote-bs4.min.css' %}">
</head>

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="{% url 'purchase_data:index' %}" class="nav-link">Home</a>
                </li>
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li>
                    <a class="nav-link">ユーザ名：{{ user.get_username }}</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'account_logout' %}">
                        <i class="fa fa-fw fa-sign-out"></i>ログアウト</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" data-widget="control-sidebar" data-controlsidebar-slide="true" href="#" role="button">
                        <i class="fas fa-th-large"></i>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="{% url 'purchase_data:index' %}" class="brand-link">
                <img src="{% static 'images/mietomaLogo.png' %}" alt="mietoma Logo" height="90px;" style="opacity: .8">
                <!--<span class="brand-text font-weight-light">みえとま</span>-->
            </a>

            <!-- Sidebar -->
            <div class="sidebar">

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
                        <li class="nav-item">
                            <a href="{% url 'purchase_data:index' %}" class="nav-link active">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Dashboard
                                </p>
                            </a>
                        </li>
                        <li class="nav-item menu-open">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-table"></i>
                                <p>
                                    購買データ
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="{% url 'purchase_data:purchase_data_create' %}" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>購買データの登録</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'purchase_data:purchase_data_list' %}" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>購買データの一覧</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item menu-open">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-table"></i>
                                <p>
                                    商品
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="{% url 'purchase_data:item_create' %}" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>商品の登録</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'purchase_data:item_list' %}" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>商品の一覧</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            {% block extra_head %} {% endblock %}
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    {% block content %} {% endblock %}
                </div>
                <!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <footer class="main-footer">
            <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 3.2.0
            </div>
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->

    <!-- jQuery -->
    <script src="{% static 'AdminLTE-3.2.0/plugins/jquery/jquery.min.js' %}"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="{% static 'AdminLTE-3.2.0/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'AdminLTE-3.2.0/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- ChartJS -->
    <script src="{% static 'AdminLTE-3.2.0/plugins/chart.js/Chart.min.js' %}"></script>
    <!-- Sparkline -->
    <script src="{% static 'AdminLTE-3.2.0/plugins/sparklines/sparkline.js' %}"></script>
    <!-- JQVMap -->
    <script src="{% static 'AdminLTE-3.2.0/plugins/jqvmap/jquery.vmap.min.js' %}"></script>
    <script src="{% static 'AdminLTE-3.2.0/plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
    <!-- jQuery Knob Chart -->
    <script src="{% static 'AdminLTE-3.2.0/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
    <!-- daterangepicker -->
    <script src="{% static 'AdminLTE-3.2.0/plugins/moment/moment.min.js' %}"></script>
    <script src="{% static 'AdminLTE-3.2.0/plugins/daterangepicker/daterangepicker.js' %}"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="{% static 'AdminLTE-3.2.0/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
    <!-- Summernote -->
    <script src="{% static 'AdminLTE-3.2.0/plugins/summernote/summernote-bs4.min.js' %}"></script>
    <!-- overlayScrollbars -->
    <script src="{% static 'AdminLTE-3.2.0/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'AdminLTE-3.2.0/dist/js/adminlte.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <!-- <script src="{% static 'AdminLTE-3.2.0/dist/js/demo.js' %}"></script> -->
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="{% static 'AdminLTE-3.2.0/dist/js/pages/dashboard.js' %}"></script>

</body>

</html>

templates/index.html
{% extends 'base.html' %} {% block extra_head %}
<h1 class="m-0">Dashboard</h1>
{% endblock %} {% block content %}

<!-- Small boxes (Stat box) -->
<div class="row">
    <div class="col-lg-5 col-6">
        <!-- small box -->
        <div class="small-box bg-info">
            <div class="inner">
                <h3>購買データ</h3>
                <p>取引のデータの登録、可視化したデータの閲覧はこちらから</p>
            </div>

            <a href="{% url 'purchase_data:purchase_data_create' %}" class="small-box-footer">登録 <i class="fas fa-arrow-circle-right"></i></a>
            <a href="{% url 'purchase_data:purchase_data_list' %}" class="small-box-footer">一覧を見る <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-5 col-6">
        <!-- small box -->
        <div class="small-box bg-gradient-success">
            <div class="inner">
                <h3>商品</h3>
                <p>取り扱っている商品の登録、登録商品の確認はこちらから</p>
            </div>
            <a href="{% url 'purchase_data:item_create' %}" class="small-box-footer">登録 <i class="fas fa-arrow-circle-right"></i></a>
            <a href="{% url 'purchase_data:item_list' %}" class="small-box-footer">一覧を見る <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
</div>
<!-- /.row -->

{% endblock %}