config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('purchase_data.urls', namespace='purchase_data')),
    path('accounts/', include('allauth.urls')),
   # path('', include('accounts.urls')), 
]

purchase_data/urls.py
from django.urls import path
from . import views
 
app_name = 'purchase_data'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    #path('index/', views.IndexView.as_view(), name='index'),
    path('item/create/', views.ItemCreateView.as_view(), name='item_create'),
    path('item/create/complete', views.ItemCreateCompleteView.as_view(), name='item_create_complete'),
    path('item/list/', views.ItemListView.as_view(),name='item_list'),
    path('item/detail/<uuid:pk>/', views.ItemDetailView.as_view(), name='item_detail'), 
    path('item/update/<uuid:pk>/', views.ItemUpdateView.as_view(), name='item_update'),
    path('item/delete/<uuid:pk>/', views.ItemDeleteView.as_view(), name='item_delete'),
    path('purchase_data/create/', views.PurchaseDataCreateView.as_view(), name='purchase_data_create'),
    path('purchase_data/create/complete', views.PurchaseDataCreateCompleteView.as_view(), name='purchase_data_create_complete'),
    path('purchase_data/list/', views.PurchaseDataListView.as_view(),name='purchase_data_list'),
    path('purchase_data/detail/<uuid:pk>/', views.PurchaseDataDetailView.as_view(), name='purchase_data_detail'), 
    path('purchase_data/update/<uuid:pk>/', views.PurchaseDataUpdateView.as_view(), name='purchase_data_update'),
    path('purchase_data/delete/<uuid:pk>/', views.PurchaseDataDeleteView.as_view(), name='purchase_data_delete'),
]

purchase_data_Tomakomai/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

templates/item/item_create.html
{% extends 'base.html' %} {% load widget_tweaks %} {% block extra_head %}
<h1 class="m-0">商品の登録</h1>
{% endblock %} {% block content %}
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        <label>{{ form.name.label }}</label> {{ form.name | add_class:'form-control col-2' }}
    </div>
    <div class="form-group">
        <label>{{ form.price.label }}</label> {{ form.price | add_class:'form-control col-2' }}
    </div>
    <div class="form-group">
        <label>{{ form.category.label }}</label> {{ form.category | add_class:'form-control col-2' }}
    </div>
    <button type="submit" name="submit">登録</button>
</form>

{% endblock %}

templates/item/item_create_complete.html
{% extends 'base.html' %} {% block content %}
<p>購買データの登録が完了しました！</p>
<a href="{% url 'purchase_data:index' %}">トップへ戻る</a> {% endblock %}

templates/item/item_delete.html
{% extends 'base.html' %} {% block content %}
<h1>商品の削除</h1>
<form method="post">
    {% csrf_token %}
    <p>{{ purchase_data.id }} {{ purchase_data.date }} を削除します</p>
    <input type="submit" value="削除">
</form>
{% endblock %}

templates/item/item_detail.html
{% extends 'base.html' %} {% block content %}
<p>{{ item.id }}</p>
<p>{{ item.name }}</p>
<p>{{ item.price }}</p>
<p>{{ item.category }}</p>
<a href="{% url 'purchase_data:item_update' item.pk %}">編集</a>
<a href="{% url 'purchase_data:item_delete' item.pk %}">削除</a>
<a href="{% url 'purchase_data:index' %}">戻る</a> {% endblock %}

templates/item/item_list.html
{% extends 'base.html' %}{% block extra_head %}
<h1 class="m-0">商品の一覧</h1>
{% endblock %} {% block content %}
<div class="main">
    <table>
        <tr>
            <th>商品名</th>
            <th>金額</th>
            <th>カテゴリー</th>
        </tr>
        {% for i in item_list %}
        <tr>
            <td>{{ i.name }}</td>
            <td>{{ i.price }}円</td>
            <td>{{ i.category }}</td>
            <td><a href="{% url 'purchase_data:item_update' i.pk %}">編集</a></td>
            <td><a href="{% url 'purchase_data:item_delete' i.pk %}">削除</a></td>
        </tr>
        {% endfor %}
    </table>
</div>
<a href="{% url 'purchase_data:index' %}">戻る</a> {% endblock %}

templates/item/item_update.html
{% extends 'base.html' %} {% block content %}
<h1>商品の編集</h1>
<form method="post">
    {% csrf_token %} {{ form.as_p }}
    <input type="submit" value="保存">
</form>
{% endblock %}